version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    expose:
      - 3306
      - 33060
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    networks:
      - internal
    ports:
      - 3306:3306
      - 33060:33060

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ./redis-cache:/data
    networks:
      - internal
    expose:
      - 3000

  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elastic
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - internal
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  nginx:
    build: ./nginx-docker
    container_name: nginx
    depends_on:
      - php
    volumes:
      - shared-volume:/var/www/html
    networks:
      - internal
    expose:
      - 8080
      - 80
    ports:
      - 80:80
      - 8080:8080

  rabbit:
    image: rabbitmq:3.9-management
    container_name: rabbit
    hostname: my-rabbit
    volumes:
      - ./rabbit-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - internal
    environment:
      - RABBITMQ_DEFAULT_USER=magento
      - RABBITMQ_DEFAULT_PASS=magento

  php:
    build: .
    container_name: php
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - rabbit
    volumes:
      - shared-volume:/var/www/html
    networks:
      - internal
    expose:
      - 9000
    ports:
      - 9000:9000
networks:
  internal:
    name: internal
    driver: bridge

volumes:
  shared-volume:
