version: '3.8'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./mysql-data:/var/lib/mysql
    expose:
      - 3306
      - 33060
    environment:
      - MYSQL_ROOT_PASSWORD=adminadminadmin
    networks:
      - internal
    ports:
      - 3306:3306
      - 33060:33060

  redis:
    image: redis:6.2
    volumes:
      - ./redis-cache:/data
    networks:
      - internal
    expose:
      - 3000

  elasticsearch:
    image: elasticsearch:7.17.7
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - internal
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx-data:/etc/nginx
    networks:
      - internal
    expose:
      - 8080
      - 80
    ports:
      - 80:80
      - 8080:8080

networks:
  internal:
    name: internal
    driver: bridge
