version: '3.8'

services:
  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx-data:/etc/nginx
    networks:
      - internal
    expose:
      - 8080
      - 80

networks:
  internal:
    name: internal
    external: true
